-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/GlobalMessages/schema/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/global_messages_cache (
  gmc_page_id INT UNSIGNED NOT NULL,
  gmc_name VARBINARY(255) NOT NULL,
  gmc_lang VARBINARY(35) NOT NULL,
  gmc_text BLOB NOT NULL,
  UNIQUE INDEX gmc_by_page (gmc_page_id),
  PRIMARY KEY(gmc_page_id)
) /*$wgDBTableOptions*/;